const imgs = [
  {
    img:"./Image/1.jpg"
  },
  {
    img:"./Image/2.jpg"
  },
  {
    img:"./Image/3.jpg"
  },
  {
    img:"./Image/4.jpg"
  },
  {
    img:"./Image/5.jpg"
  },
  {
    img:"./Image/6.jpg"
  },
  {
    img:"./Image/7.jpg"
  },
  {
    img:"./Image/8.jpg"
  },
  {
    img:"./Image/9.jpg"
  },
  {
    img:"./Image/10.jpg"
  },
  {
    img:"./Image/11.jpg"
  },
  {
    img:"./Image/12.jpg"
  },
  {
    img:"./Image/13.jpg"
  },
  {
    img:"./Image/14.jpg"
  },
  {
    img:"./Image/15.jpg"
  },
  {
    img:"./Image/16.jpg"
  },
  {
    img:"./Image/17.jpg"
  },
  {
    img:"./Image/18.jpg"
  }
]

// const imgs = ["./Image/1.jpg","./Image/2.jpg","./Image/3.jpg","./Image/4.jpg","./Image/5.jpg","./Image/6.jpg","./Image/7.jpg","./Image/8.jpg","./Image/9.jpg","./Image/10.jpg","./Image/11.jpg","./Image/12.jpg","./Image/13.jpg","./Image/14.jpg","./Image/15.jpg","./Image/16.jpg","./Image/17.jpg","./Image/18.jpg"]

export default imgs;